version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "basawal-api-conversations"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gls3cd4hrabc"
s3_prefix = "basawal-api-conversations"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

