AWSTemplateFormatVersion: 2010-09-09
Description: >-
  basawal-api-conversations
Transform:
- AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 100
    MemorySize: 128
    Environment:
      Variables:
        TABLE_NAME: !Ref ConversationsTable
        ENDPOINT_OVERRIDE: !Ref EndpointOverride
Parameters:
  EndpointOverride:
    Type: String
    Default: ''
Resources:
  getAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-items.getAllItemsHandler
      Description: Get all the items from the dynamodb table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
  getByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-by-id.getByIdHandler
      Description: Get an item from dynamodb table. 
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
  putItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put-item.putItemHandler
      Description: Put an item to the dynamodb.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
  ConversationsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"